# version: '3.9'
services:
    db:
      image: mongo
      container_name: db
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=user
      ports:
        - "27017:27017"
      volumes:
        - ./dbdata:/data/db